# Create Go Docker image build and publish stages.
parameters:
  extraParameters: {}

stages:
  - template: /eng/common/templates/stages/build-and-test.yml@self
    parameters:
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group build
      noCache: true
      # Template paths must be relative to the YAML job that executes them
      customGenerateMatrixInitSteps:
        - template: /eng/pipeline/steps/set-public-source-branch-var.yml@self
      customBuildInitSteps:
        - template: /eng/pipeline/steps/set-imagebuilder-build-args-var.yml@self
        - template: /eng/pipeline/steps/set-public-source-branch-var.yml@self

      # Windows builds often take almost exactly 60 minutes, which is the default timeout.
      # This causes flakiness. Extend the timeout for leeway.
      windowsAmdBuildJobTimeout: 90 # minutes

      # Linux AMD64
      linuxAmd64Pool:
        ${{ if ne(parameters.extraParameters.linuxAmd64Pool, '') }}:
          ${{ parameters.extraParameters.linuxAmd64Pool }}
        ${{ elseif eq(variables['System.TeamProject'], parameters.extraParameters.publicProjectName) }}:
          vmImage: $(defaultLinuxAmd64PoolImage)
        ${{ elseif eq(variables['System.TeamProject'], parameters.extraParameters.internalProjectName) }}:
          name: $(linuxAmd64InternalPoolName)
          image: $(linuxAmd64InternalPoolImage)
          os: linux

      # Linux Arm64
      linuxArm64Pool:
        os: linux
        hostArchitecture: Arm64
        image: $(linuxArm64PoolImage)
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.publicProjectName) }}:
          name: $(linuxArm64PublicPoolName)
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.internalProjectName) }}:
          name: $(linuxArm64InternalPoolName)

      # Linux Arm32
      linuxArm32Pool:
        os: linux
        hostArchitecture: Arm64
        image: $(linuxArm32PoolImage)
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.publicProjectName) }}:
          name: $(linuxArm32PublicPoolName)
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.internalProjectName) }}:
          name: $(linuxArm32InternalPoolName)

      # Windows Server 2016
      windows2016Pool:
        os: windows
        name: $(windowsServer2016PoolName)
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.publicProjectName) }}:
          image: $(windowsServer2016PublicPoolImage)
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.internalProjectName) }}:
          image: $(windowsServer2016InternalPoolImage)

      # Windows Server 2019 (1809)
      windows1809Pool:
        os: windows
        name: $(windowsServer2019PoolName)
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.publicProjectName) }}:
          image: $(windowsServer2019PublicPoolImage)
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.internalProjectName) }}:
          image: $(windowsServer2019InternalPoolImage)

      # Windows Server 2022
      windows2022Pool:
        os: windows
        name: $(windowsServer2022PoolName)
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.publicProjectName) }}:
          image: $(windowsServer2022PublicPoolImage)
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.internalProjectName) }}:
          image: $(windowsServer2022InternalPoolImage)

      # Windows Server 2025
      windows2025Pool:
        os: windows
        name: $(windowsServer2025PoolName)
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.publicProjectName) }}:
          image: $(windowsServer2025PublicPoolImage)
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.internalProjectName) }}:
          image: $(windowsServer2025InternalPoolImage)

      ${{ each pair in parameters.extraParameters }}:
        ${{ pair.key }}: ${{ pair.value }}

  - template: /eng/common/templates/stages/publish.yml@self
    parameters:
      pool:
        ${{ if ne(parameters.extraParameters.pool, '') }}:
          ${{ parameters.extraParameters.pool }}
        ${{ elseif eq(variables['System.TeamProject'], parameters.extraParameters.publicProjectName) }}:
          vmImage: $(defaultLinuxAmd64PoolImage)
        ${{ elseif eq(variables['System.TeamProject'], parameters.extraParameters.internalProjectName) }}:
          name: $(linuxAmd64InternalPoolName)
          image: $(linuxAmd64InternalPoolImage)
          os: linux

      customPublishInitSteps:
        - template: /eng/pipeline/steps/set-public-source-branch-var.yml@self

      ${{ each pair in parameters.extraParameters }}:
        ${{ pair.key }}: ${{ pair.value }}
