# Create Go Docker image build and publish stages.
parameters:
  internalProjectName: null
  publicProjectName: null
  extraParameters: {}

stages:
  - template: ../../common/templates/stages/build-test-publish-repo.yml
    parameters:
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group build
      noCache: true
      internalProjectName: ${{ parameters.internalProjectName }}
      publicProjectName: ${{ parameters.publicProjectName }}
      # Template paths must be relative to the YAML job that executes them
      customBuildInitSteps:
        - template: ../../../pipeline/steps/set-public-source-branch-var.yml
      customPublishInitSteps:
        - template: ../../../pipeline/steps/set-public-source-branch-var.yml

      # Linux AMD64
      linuxAmd64Pool:
        ${{ if eq(variables['System.TeamProject'], parameters.publicProjectName) }}:
          vmImage: $(defaultLinuxAmd64PoolImage)
        ${{ elseif eq(variables['System.TeamProject'], parameters.internalProjectName) }}:
          name: NetCore1ESPool-Internal
          image: 1es-ubuntu-2204
          os: linux
          
      # Linux Arm64
      linuxArm64Pool:
        os: linux
        hostArchitecture: Arm64
        image: Mariner-2-Docker-ARM64
        ${{ if eq(variables['System.TeamProject'], parameters.publicProjectName) }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], parameters.internalProjectName) }}:
          name: Docker-Linux-Arm-Internal

      # Linux Arm32
      linuxArm32Pool:
        os: linux
        hostArchitecture: Arm64
        image: Mariner-2-Docker-ARM64
        ${{ if eq(variables['System.TeamProject'], parameters.publicProjectName) }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], parameters.internalProjectName) }}:
          name: Docker-Linux-Arm-Internal

      # Windows Server 2016
      windows2016Pool:
        os: windows
        name: Docker-2016-${{ variables['System.TeamProject'] }}
        ${{ if eq(variables['System.TeamProject'], parameters.internalProjectName) }}:
          image: Server2016-NESDockerBuilds-PT

      # Windows Server 2019 (1809)
      windows1809Pool:
        os: windows
        name: Docker-1809-${{ variables['System.TeamProject'] }}
        ${{ if eq(variables['System.TeamProject'], parameters.internalProjectName) }}:
          image: Server2019-1809-NESDockerBuilds-1ESPT

      # Windows Server 2022
      windows2022Pool:
        os: windows
        name: Docker-2022-${{ variables['System.TeamProject'] }}
        ${{ if eq(variables['System.TeamProject'], parameters.internalProjectName) }}:
          image: Server2022-NESDockerBuilds-1ESPT

      ${{ each pair in parameters.extraParameters }}:
        ${{ pair.key }}: ${{ pair.value }}
