# Check that Dockerfile generation using "geninfra" is repeatable. This makes
# sure the manifest.json file is up to date and will build the correct images.
parameters:
  - name: pool
    type: object

stages:
  - stage: Repeatability
    dependsOn: []
    jobs:
      - job: Test
        pool: ${{ parameters.pool }}
        workspace:
          clean: all
        steps:
          - template: ../steps/checkout-unix-task.yml

          - task: GoTool@0
            displayName: 'Install Go'
            inputs:
              version: '1.26'
              goDownloadUrl: 'https://aka.ms/golang/release/latest'
          
          - script: go test ./...
            displayName: Run Go tests
