# Check that Dockerfile generation using "geninfraimagesmanifest" is repeatable. This makes sure the
# manifest.json file is up to date and will build the correct images.
parameters:
  extraParameters: {}

stages:
  - stage: Repeatability
    dependsOn: []
    jobs:
      - job: Test
        pool:
          # This is a utility job: use generic recent LTS.
          ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.publicProjectName) }}:
            name: NetCore-Public
            demands: ImageOverride -equals 1es-ubuntu-2004-open
          ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.internalProjectName) }}:
            name: NetCore1ESPool-Internal
            demands: ImageOverride -equals 1es-ubuntu-2004
        workspace:
          clean: all
        steps:
          - template: ../steps/checkout-unix-task.yml

          - task: GoTool@0
            inputs:
              version: 1.20

          - script: go run ./cmd/geninfraimagesmanifest
            displayName: Run geninfraimagesmanifest

          - script: |
              set -eux
              # Add files, so new untracked files don't evade detection.
              git add .
              # Exit code 1 = differences, 0 = no differences.
              git diff --cached --exit-code -- src manifest.json
            displayName: Ensure no changes
