# Check that Dockerfile generation using "geninfra" is repeatable. This makes
# sure the manifest.json file is up to date and will build the correct images.
parameters:
  - name: pool
    type: object

stages:
  - stage: Repeatability
    dependsOn: []
    jobs:
      - job: Test
        pool: ${{ parameters.pool }}
        workspace:
          clean: all
        steps:
          - template: ../steps/checkout-unix-task.yml

          - task: GoTool@0
            inputs:
              version: 1.22.11

          - script: go run ./cmd/geninfra
            displayName: Run geninfra

          - script: |
              set -eux
              # Add files, so new untracked files don't evade detection.
              git add .
              # Exit code 1 = differences, 0 = no differences.
              git diff --cached --exit-code -- src manifest.json
            displayName: Ensure no changes
