trigger:
  batch: true
  branches:
    include:
      - main
pr: none
schedules:
  - cron: '0 10 * * Tue,Thu'
    displayName: Periodic build to refresh dependencies
    branches:
      include:
        - main
    always: true

variables:
  - template: variables/common.yml

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Internal
        image: 1es-windows-2022
        os: windows
      tsa:
        enabled: true
        configFile: $(Build.SourcesDirectory)/.config/tsa/tsaoptions.json
    stages:
      - template: stages/build-test-publish-repo.yml
        parameters:
          extraParameters:
            # "variables.x" template expression only gets the correct value in this pipeline file. In a
            # stage template, it returns an empty string. So, evaluate it here and pass it through.
            internalProjectName: ${{ variables.internalProjectName }}
            publicProjectName: ${{ variables.publicProjectName }}
