trigger: none
pr:
  branches:
    include:
      - main

variables:
  - template: variables/common.yml

stages:
  - template: /eng/common/templates/stages/dotnet/publish-config-nonprod.yml@self
    parameters:
      sourceBuildPipelineRunId: $(Build.BuildId)
      stagesTemplate: /eng/common/templates/stages/dotnet/build-and-test.yml@self
      stagesTemplateParameters:
        sourceBuildPipelineRunId: $(Build.BuildId)
        buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group build
        noCache: true
        customGenerateMatrixInitSteps:
          - template: /eng/pipeline/steps/set-public-source-branch-var.yml@self
        customBuildInitSteps:
          - template: /eng/pipeline/steps/set-imagebuilder-build-args-var.yml@self
          - template: /eng/pipeline/steps/set-public-source-branch-var.yml@self
        buildMatrixType: platformVersionedOs

  - template: stages/check-generation-repeatable.yml
    parameters:
      pool:
        name: NetCore-Public
        demands: ImageOverride -equals 1es-ubuntu-2004-open
