trigger:
  batch: true
  branches:
    include:
      - main
pr: none
schedules:
  - cron: '0 10 * * Tue,Thu'
    displayName: Periodic build to refresh dependencies
    branches:
      include:
        - main
    always: true

parameters:
  - name: sourceBuildPipelineRunId
    displayName: >
      The build ID of this pipeline to publish images from.
      Use the default value when building new images.
    type: string
    default: '$(Build.BuildId)'

variables:
  - template: variables/common.yml
    parameters:
      sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  ${{ if variables['Go1ESOfficial'] }}:
    template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  ${{ else }}:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Internal
        image: 1es-windows-2022
        os: windows
      tsa:
        enabled: true
        configFile: $(Build.SourcesDirectory)/.config/tsa/tsaoptions.json
    stages:
      - template: /eng/common/templates/stages/setup-service-connections.yml@self
        parameters:
          pool:
            name: $(default1ESInternalPoolName)
            image: $(default1ESInternalPoolImage)
            os: linux
          serviceConnections:
            - name: $(internal-mirror.serviceConnectionName)
            - name: $(build.serviceConnectionName)
            - name: $(publish.serviceConnectionName)
            - name: $(marStatus.serviceConnectionName)
            - name: $(kusto.serviceConnectionName)
      - template: stages/build-test-publish-repo.yml
        parameters:
          extraParameters:
            # "variables.x" template expression only gets the correct value in this pipeline file. In a
            # stage template, it returns an empty string. So, evaluate it here and pass it through.
            internalProjectName: ${{ variables.internalProjectName }}
            publicProjectName: ${{ variables.publicProjectName }}
            sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
