trigger:
  batch: true
  branches:
    include:
      - main
pr: none
schedules:
  - cron: '0 10 * * Tue,Thu'
    displayName: Periodic build to refresh dependencies
    branches:
      include:
        - main
    always: true

parameters:
  - name: sourceBuildPipelineRunId
    displayName: >
      The build ID of this pipeline to publish images from.
      Use the default value when building new images.
    type: string
    default: '$(Build.BuildId)'

  - name: publishRepoPrefix
    displayName: >
      Publish repo prefix to use when publishing images.
      Switch to "dev/" for an unofficial branch.
    type: string
    default: 'unlisted/'

variables:
  - template: variables/common.yml
    parameters:
      sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

    - repository: VersionsRepo
      type: git
      name: microsoft-go-images-versions
      ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

extends:
  ${{ if variables['Go1ESOfficial'] }}:
    template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  ${{ else }}:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Internal
        image: 1es-windows-2022
        os: windows
      sourceRepositoriesToScan:
        include:
          - repository: VersionsRepo
      tsa:
        enabled: true
        configFile: $(SDLConfigFileDir)/tsa/tsaoptions.json
    stages:
      - template: /eng/common/templates/stages/setup-service-connections.yml@self
        parameters:
          pool:
            name: $(default1ESInternalPoolName)
            image: $(default1ESInternalPoolImage)
            os: linux
          serviceConnections:
            - name: $(internal-mirror.serviceConnectionName)
            - name: $(build.serviceConnectionName)
            - name: $(publish.serviceConnectionName)
            - name: $(marStatus.serviceConnectionName)
            - name: $(kusto.serviceConnectionName)

      - template: /eng/common/templates/stages/dotnet/publish-config-prod.yml@self
        parameters:
          sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
          publishRepoPrefix: ${{ parameters.publishRepoPrefix }}
          stagesTemplate: /eng/common/templates/stages/dotnet/build-test-publish-repo.yml@self
          stagesTemplateParameters:
            sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
            buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group build
            versionsRepoRef: VersionsRepo
            noCache: true
            customGenerateMatrixInitSteps:
              - template: /eng/pipeline/steps/set-public-source-branch-var.yml@self
            customBuildInitSteps:
              - template: /eng/pipeline/steps/set-imagebuilder-build-args-var.yml@self
              - template: /eng/pipeline/steps/set-public-source-branch-var.yml@self
            customPublishInitSteps:
              - template: /eng/pipeline/steps/set-public-source-branch-var.yml@self
              - pwsh: echo "##vso[task.setvariable variable=SDLConfigFileDir]$(SDLConfigFileMultiRepoDir)"
                displayName: 'Set SDLConfigFileDir for multi-checkout'
