trigger:
  batch: true
  branches:
    include:
      - main
pr: none

variables:
  - template: variables/common.yml

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NetCore1ESPool-Internal
      image: 1es-windows-2022
      os: windows
    stages:
      - template: stages/build-test-publish-repo.yml
        parameters:
          # "variables.x" template expression only gets the correct value in this pipeline file. In a
          # stage template, it returns an empty string. So, evaluate it here and pass it through.
          internalProjectName: ${{ variables.internalProjectName }}
          publicProjectName: ${{ variables.publicProjectName }}
