# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline runs rolling validation, like CodeQL.

# official: https://dev.azure.com/dnceng/internal/_build?definitionId=1358
# unofficial: https://dev.azure.com/dnceng/internal/_build?definitionId=1516

pipelineymlgen:
  output:
    - file: ${ trimSuffix ".gen.yml" .filename }-pipeline-unofficial.yml
      data:
        official: false
    - file: ${ trimSuffix ".gen.yml" .filename }-pipeline.yml
      data:
        official: true
---

trigger: none
pr: none

# For info about runtime parameters, see https://github.com/microsoft/go-infra/blob/main/docs/pipeline-yml-style.md#runtime-parameters
parameters:
  - name: enableCodeQL
    displayName: '[Debug input] Enable CodeQL, even on a dev branch.'
    type: boolean
    default: ${ yml (not .official) }

  - name: disableTSA
    displayName: '[Debug input] Disable TSA reporting. Use to try modifications in dev branches.'
    type: boolean
    default: ${ yml (not .official) }

variables:
  - name: Codeql.PublishDatabase
    value: true
  - name: Codeql.PublishDatabaseLog
    value: true
  - name: Codeql.PublishDatabaseLog
    value: true
  - ${{ if parameters.enableCodeQL }}:
    # The default cadence is ok for official branches. The cadence is per-branch.
    # For a dev build, the cadence would prevent dev iteration.
    # https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/codeql-general-faq#how-do-i-check-if-my-project-is-onboarded
    - name: Codeql.Cadence
      value: 0

resources:
  pipelines:
    - pipeline: build
      source: microsoft-go-infra-images-nightly (official)
      ${ inlineif .official }:
        trigger:
          branches:
            include:
              - main
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  ${ inlineif .official }:
    template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  ${ inlineelse }:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NetCore1ESPool-Internal
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
        enabledOnNonDefaultBranches: ${{ parameters.enableCodeQL }}
        language: go,powershell
      tsa:
        enabled: ${{ not(parameters.disableTSA) }}
        configFile: $(Build.SourcesDirectory)/.config/tsa/tsaoptions.json

    stages:
      - stage: Analyze
        jobs:
          - job: Analyze
            workspace:
              clean: all
            steps:
              - task: GoTool@0
                inputs:
                  version: 1.24.0

              - script: |
                  go build ./...
                displayName: go

              # Build no images, but exercise the PowerShell scripts.
              - script: |
                  pwsh build.ps1 -Paths build_no_images
                displayName: pwsh
